# .github/workflows/test.yml
# ... existing config

- name: Run tests with coverage
  run: pnpm test:coverage

# Optional: Add a step to upload coverage reports
- name: Upload coverage reports
  uses: codecov/codecov-action@v3
  # You'll need to sign up for codecov.io and add CODECOV_TOKEN to your GitHub secrets
  # with:
  #   token: ${{ secrets.CODECOV_TOKEN }}name: ThriveSend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: pnpm test || echo "No tests found, add tests to your project"